### ISSUE TITLE
Hello,Will the code be open ？

### ISSUE THREAD

**Issue by shoukailiang** [cgsaxner/HL2ToolTracking#1]
Hello,Will the code be open ？

**Comment by cgsaxner** [comment]
Hi! 
I'm sorry that it took so long, but the first part of the code is now released. Since I currently have restricted access to a HL2 and am working on other projects, cleaning the code takes longer than expected. I hope that you already find the available content useful and I will update the repository in the near future.

**Comment by shoukailiang** [comment]
OK, I'm glad to hear from you.
